apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-fail
spec:
  containers:
  - name: nginx-container-1
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx-container-2
    image: nginx
    ports:
    - containerPort: 80